config/routes.rb
Rails.application.routes.draw do

  get  'show',   to: 'pages#show'
  post 'create', to: 'pages#create'

  root to: 'pages#index'

  get "*path", to: redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def create
    if params[:username].present?
      redirect_to show_path(params[:username])
    else
      redirect_to :root, alert: "Please insert a GitHub Username"
    end
  end

  def show
    user = fetch_user(params["format"])

    redirect_to_root unless user.repos.present?

    info_hash = user.fetch_username_avatar_url
    @top_lang = user.fetch_top_n_repos_languages

    # Rename "JS" for ShowPage Layout purpose
    if @top_lang.key? "JavaScript"
      @top_lang["JS"] = @top_lang.delete("JavaScript")
    end

    set_user(info_hash)
  end

private

  def fetch_user(username)
    FetchGithubApi.new(username)
  end

  def set_user(info)
    @avatar   = info["avatar"]
    @url      = info["url"]
    @username = info["username"]
  end

  def redirect_to_root
    redirect_to :root, alert: "USER NOT FOUND"; return
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GitHubSearch</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" integrity="sha256-PF6MatZtiJ8/c9O9HQ8uSUXr++R9KBYu4gbNG5511WE=" crossorigin="anonymous" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300&display=swap" rel="stylesheet">

    <%= javascript_include_tag 'application' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_responsive-card.html.erb
<div class="my-card flex-center">
  <img src="<%= image_path('horse-js.png') %>" class="my-avatar" />
  <div class="my-card-content">
    <p><strong>horse_js</strong></p>
    <p>as much as I want to be, I'm not <span class="horse-text">@horse_js</span></p>
  </div>

  <div class="my-card-days">
    <small>7 days</small>
  </div>
</div>

app/views/pages/index.html.erb
<div class="wrapper">

  <div id="white-top" class="flex-center">

    <div id="content">

      <div class="text-center">
        <h3 id="title">TITLE</h3>
        <p id="subtitle">s u b t i t l e</p>
      </div>

      <div id="form-action">
        <%= form_tag create_path, id: "my-form" do %>

          <%= text_field_tag :username, params[:username],
            placeholder: "GitHub username" %>

          <%= submit_tag "Search",
            class: "btn btn-large btn-outline-secondary my-pad" %>

        <% end %>
      </div>

    </div>

  </div>


  <div id="dark-bottom" class="flex-center">
    <div id="card-wrapper" class="flex-center">
      <%= render "responsive-card" %>
    </div>
  </div>

</div>

app/views/pages/show.html.erb
<div class="wrapper d-flex position-relative">

  <div id="white-left">


    <h2 id="username" class="text-center">
      <%= @username %>
    </h2>

    <%= image_tag @avatar, class: "github-avatar roll-in-left" %>

    <p>
      <%= link_to "<i class='fab fa-github'></i>".html_safe, @url, target: "_blank", id: "github-link" %>
    </p>

    <%= link_to "New Search", root_path, id: "root-btn", class: "btn btn-large btn-outline-secondary my-pad"  %>
  </div>

  <div id="dark-right">
    <% @top_lang.each do |k,_| %>
      <div class="circle flex-center bounce-top">
        <%= k %>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<!--   <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div> -->
<% end %>
<% if alert %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><strong>Mmh</strong> 🤔 username not valid. Try again</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>